const Router = require('express')
const router = new Router()

const userRoutes = require('./authRoutes')
const personalRoutes = require('./personalRoutes')
const merchandiseRoutes = require('./merchandiseRoutes')
const newsRoutes = require('./newsRoutes')
const clubRoutes = require('./clubRoutes')
const matchRoutes = require('./matchRoutes')
const commentRoutes = require('./commentsRoutes')
const playerRoutes = require('./playerRoutes')
const galleryRoutes = require('./galleryRoutes')
const personal = require('./mainRoutes')
const cartRoutes = require('./cartRoutes')
const orderRoutes = require('./orderRoutes')
const historyRoutes = require('./historyChapterRoutes')
const videoRoutes = require('./videoRoutes')

router.use('/user', userRoutes)
router.use('/personals', personalRoutes)
router.use('/merchandise', merchandiseRoutes)
router.use('/news', newsRoutes)
router.use('/clubs', clubRoutes)
router.use('/match', matchRoutes)
router.use('/comment', commentRoutes)
router.use('/player', playerRoutes)
router.use('/gallery', galleryRoutes)
router.use('/personal', personal)
router.use('/cart', cartRoutes)
router.use('/order', orderRoutes)
router.use('/history', historyRoutes)
router.use('/video', videoRoutes)

module.exports = router
